//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace k3k.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fisikotherapeftis
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Fisikotherapeftis()
        {
            this.Sinedries = new HashSet<Sinedries>();
        }
    
        public int FisikotherapeftisId { get; set; }
        public string Eponimo { get; set; }
        public string Onoma { get; set; }
        public string Patronimo { get; set; }
        public string Stathero { get; set; }
        public string Kinito { get; set; }
        public string email { get; set; }
        public string Afm { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sinedries> Sinedries { get; set; }
    }
}
