//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace k3k.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int UserId { get; set; }
        public string Eponimo { get; set; }
        public string Onoma { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public Nullable<int> IdiotitaId { get; set; }
        public Nullable<int> EpipedoId { get; set; }
    
        public virtual UserEpipedo UserEpipedo { get; set; }
        public virtual UserIdiotita UserIdiotita { get; set; }
    }
}
