//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3k.Domain
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CustomerEntities : DbContext
    {
        public CustomerEntities()
            : base("name=CustomerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Asthenis> Asthenis { get; set; }
        public virtual DbSet<Filo> Filo { get; set; }
        public virtual DbSet<Financial> Financial { get; set; }
        public virtual DbSet<Fisikotherapeftis> Fisikotherapeftis { get; set; }
        public virtual DbSet<Giatros> Giatros { get; set; }
        public virtual DbSet<Parapemptiko> Parapemptiko { get; set; }
        public virtual DbSet<SeiraParastatiko> SeiraParastatiko { get; set; }
        public virtual DbSet<Sinedries> Sinedries { get; set; }
    }
}
