//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3k.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sinedries
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sinedries()
        {
            this.Financial = new HashSet<Financial>();
        }
    
        public int SinedriesId { get; set; }
        public Nullable<int> AsthenisId { get; set; }
        public Nullable<int> ParapemptikoId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> FisikotherapeftisId { get; set; }
        public string Paratirisis { get; set; }
        public Nullable<decimal> Poso { get; set; }
        public Nullable<System.TimeSpan> time { get; set; }
    
        public virtual Asthenis Asthenis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Financial> Financial { get; set; }
        public virtual Fisikotherapeftis Fisikotherapeftis { get; set; }
        public virtual Parapemptiko Parapemptiko { get; set; }
    }
}
